// TypeScript OpenNext config for CI (Cloudflare adapter)
// Mirrors the CommonJS config to satisfy CLI filename expectations.
export default {
  default: {
    // where OpenNext will write worker and assets
    output: '.open-next',
    // Cloudflare adapter package
    adapter: '@opennextjs/cloudflare',
    // allow overriding project name via env in CI
    project: process.env.CLOUDFLARE_PROJECT_NAME || undefined,
    // adapter/runtime overrides required by the Cloudflare adapter
    override: {
      wrapper: 'cloudflare-node',
      converter: 'edge',
      proxyExternalRequest: 'fetch',
      incrementalCache: 'dummy',
      tagCache: 'dummy',
      queue: 'dummy',
    },
    // Only copy SSR chunk files that exist to avoid ENOENT errors
    copy: {
      // Copy all present SSR chunks, but skip missing ones
      'server/chunks/ssr': [
        '[externals]_next_dist_shared_lib_no-fallback-error_external_59b92b38.js',
        '[externals]_sharp_4f623ccc._.js',
        '[root-of-the-server]__296a25b5._.js',
        '[root-of-the-server]__334aff55._.js',
        '[root-of-the-server]__3cd453cb._.js',
        '[root-of-the-server]__48c81717._.js',
        '[root-of-the-server]__5ea3dff5._.js',
        '[root-of-the-server]__5fa1dc8c._.js',
        '[root-of-the-server]__79f61b9f._.js',
        '[root-of-the-server]__961193e0._.js',
        '[root-of-the-server]__9c314483._.js',
        '[root-of-the-server]__9fe72a73._.js',
        '[root-of-the-server]__a3e96058._.js',
        '[root-of-the-server]__c70028c2._.js',
        '[root-of-the-server]__cc44495d._.js',
        '[root-of-the-server]__d133fcd0._.js',
        '[root-of-the-server]__e57b19b4._.js',
        '[root-of-the-server]__fbf68cbb._.js',
        '[root-of-the-server]__fdefc251._.js',
        '[turbopack]_runtime.js',
        '_06286fba._.js',
        '_1ea93d49._.js',
        '_37ea37b3._.js',
        '_39b5f553._.js',
        '_3b3f5d7b._.js',
        '_8d2ee668._.js',
        '_8f2e6955._.js',
        '_96a5f8d5._.js',
        '_e2a6e339._.js',
        '_e95898a7._.js',
        '_ee622031._.js',
        '_f8032e9c._.js',
        '_next-internal_server_app_(admin)_page_actions_14cc4e02.js',
        '_next-internal_server_app__not-found_page_actions_554ec2bf.js',
        '_next-internal_server_app_about_page_actions_6fff35e4.js',
        '_next-internal_server_app_contact_page_actions_44e32ac3.js',
        '_next-internal_server_app_page_actions_39d4fc33.js',
        '_next-internal_server_app_portfolio_[slug]_page_actions_5652ee73.js',
        '_next-internal_server_app_portfolio_page_actions_224c57fe.js',
        'node_modules_4bc666ab._.js',
        'node_modules_next_dist_27e2525e._.js',
        'node_modules_next_dist_2d1fda97._.js',
        'node_modules_next_dist_6ec3f5d4._.js',
        'node_modules_next_dist_9b675e8e._.js',
        'node_modules_next_dist_ca9f65df._.js',
        'node_modules_next_dist_cc88faaa._.js',
        'node_modules_next_dist_client_components_9774470f._.js',
        'node_modules_next_dist_client_components_builtin_forbidden_45780354.js',
        'node_modules_next_dist_client_components_builtin_global-error_ece394eb.js',
        'node_modules_next_dist_client_components_builtin_unauthorized_15817684.js',
        'node_modules_next_dist_compiled_bc6b8ddf._.js',
        'node_modules_next_dist_esm_0cc614fa._.js',
        'node_modules_next_dist_esm_build_templates_app-page_1ef32f46.js',
        'node_modules_next_dist_esm_build_templates_app-page_767cdbd8.js',
        'node_modules_next_dist_esm_build_templates_app-page_d92e159d.js',
        'node_modules_next_f71b9665._.js',
      ],
    },
  },
  // ensure node:crypto is externalized in edge builds
  edgeExternals: ['node:crypto'],
  // middleware should be external and have cloudflare-edge overrides
  middleware: {
    external: true,
    override: {
      wrapper: 'cloudflare-edge',
      converter: 'edge',
      proxyExternalRequest: 'fetch',
      incrementalCache: 'dummy',
      tagCache: 'dummy',
      queue: 'dummy',
    },
  },
};
