name = "inkpup"
compatibility_date = "2025-10-07"
main = ".open-next/worker.js"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[build]
command = "npm run opennext:build"

[env.dev]
route = "dev.inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"

[env.production]
route = "inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
