name = "inkpup"
compatibility_date = "2025-10-07"
main = ".open-next/worker.js"
account_id = "3fa0a5663d51ae5473029f71cc97fa7d"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "inkpup"

[env.dev]
name = "inkpup-dev"
route = "dev.admin.inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[[env.dev.services]]
binding = "REALTIME"
service = "inkpup-realtime-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "inkpup-db-dev"
database_id = "cb636c73-b9ca-4a79-946a-e343541e878b"
migrations_dir = "scripts/db/migrations"

[[env.dev.kv_namespaces]]
binding = "CACHE"
id = "5dbe0ac9a630423ca4edc74280088fb3"

[[env.dev.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dev-bucket"

[env.dev.vars]
# Cloudflare
CF_ACCOUNT_ID = "${CF_ACCOUNT_ID}"
CF_ZONE_ID = "${CF_ZONE_ID}"
CLOUDFLARE_ANALYTICS_TOKEN = "${CLOUDFLARE_ANALYTICS_TOKEN}"
# R2 Storage
R2_ACCOUNT_ID = "${CF_ACCOUNT_ID}"
R2_BUCKET_NAME = "${R2_BUCKET}"
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
# Admin
ADMIN_PORTAL_HOSTS = "${ADMIN_PORTAL_HOSTS}"
ADMIN_PORTAL_PASSWORD = "${ADMIN_PORTAL_PASSWORD}"
ADMIN_SESSION_SECRET = "${ADMIN_SESSION_SECRET}"
# Email
CONTACT_EMAIL = "${CONTACT_EMAIL}"
RESEND_API_KEY = "${RESEND_API_KEY}"
RESEND_WEBHOOK_SECRET = "${RESEND_WEBHOOK_SECRET}"

[env.production]
name = "inkpup"
route = "inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[[env.production.services]]
binding = "REALTIME"
service = "inkpup-realtime"

[[env.production.d1_databases]]
binding = "DB"
database_name = "inkpup-db"
database_id = "fb58122f-db2f-4152-8a7a-fbfc2150d520"
migrations_dir = "scripts/db/migrations"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "4ef6330025cc495dbdc098db32c3e6f4"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "${R2_BUCKET}"

[env.production.vars]
# Cloudflare
CF_ACCOUNT_ID = "${CF_ACCOUNT_ID}"
CF_ZONE_ID = "${CF_ZONE_ID}"
CLOUDFLARE_ANALYTICS_TOKEN = "${CLOUDFLARE_ANALYTICS_TOKEN}"
# R2 Storage
R2_ACCOUNT_ID = "${CF_ACCOUNT_ID}"
R2_BUCKET_NAME = "${R2_BUCKET}"
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
# Admin
ADMIN_PORTAL_HOSTS = "${ADMIN_PORTAL_HOSTS}"
ADMIN_PORTAL_PASSWORD = "${ADMIN_PORTAL_PASSWORD}"
ADMIN_SESSION_SECRET = "${ADMIN_SESSION_SECRET}"
# Email
CONTACT_EMAIL = "${CONTACT_EMAIL}"
RESEND_API_KEY = "${RESEND_API_KEY}"
RESEND_WEBHOOK_SECRET = "${RESEND_WEBHOOK_SECRET}"
