name = "inkpup"
compatibility_date = "2025-10-07"
main = ".open-next/worker.js"
account_id = "3fa0a5663d51ae5473029f71cc97fa7d"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "inkpup-db"
database_id = "fb58122f-db2f-4152-8a7a-fbfc2150d520"

[[kv_namespaces]]
binding = "CACHE"
id = "4ef6330025cc495dbdc098db32c3e6f4"
preview_id = "5dbe0ac9a630423ca4edc74280088fb3"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "inkpup"

[[env.dev.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dev-bucket"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "${R2_BUCKET}"

[env.dev]
name = "inkpup-dev"
route = "dev.admin.inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[env.dev.vars]
R2_ACCOUNT_ID = "${R2_ACCOUNT_ID}"
R2_BUCKET_NAME = "${R2_BUCKET}"
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
CF_WEB_ANALYTICS_TOKEN = "${CF_WEB_ANALYTICS_TOKEN}"
ADMIN_PORTAL_HOSTS = "${ADMIN_PORTAL_HOSTS}"
ADMIN_PORTAL_PASSWORD = "${ADMIN_PORTAL_PASSWORD}"
ADMIN_SESSION_SECRET = "${ADMIN_SESSION_SECRET}"
CONTACT_EMAIL = "${CONTACT_EMAIL}"
RESEND_API_KEY = "${RESEND_API_KEY}"

[env.production]
name = "inkpup"
route = "inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[env.production.vars]
R2_ACCOUNT_ID = "${R2_ACCOUNT_ID}"
R2_BUCKET_NAME = "${R2_BUCKET}"
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
CF_WEB_ANALYTICS_TOKEN = "${CF_WEB_ANALYTICS_TOKEN}"
ADMIN_PORTAL_HOSTS = "${ADMIN_PORTAL_HOSTS}"
ADMIN_PORTAL_PASSWORD = "${ADMIN_PORTAL_PASSWORD}"
ADMIN_SESSION_SECRET = "${ADMIN_SESSION_SECRET}"
CONTACT_EMAIL = "${CONTACT_EMAIL}"
RESEND_API_KEY = "${RESEND_API_KEY}"
