name = "inkpup"
compatibility_date = "2025-10-07"
main = ".open-next/worker.js"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
R2_BUCKET = "${R2_BUCKET}"
CF_WEB_ANALYTICS_TOKEN = "${CF_WEB_ANALYTICS_TOKEN}"

[env.dev]
name = "inkpup-dev"
route = "dev.inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[env.dev.vars]
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
R2_BUCKET = "${R2_BUCKET}"
CF_WEB_ANALYTICS_TOKEN = "${CF_WEB_ANALYTICS_TOKEN}"

[env.production]
name = "inkpup"
route = "inkpup.ca/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
logpush = true

[env.production.vars]
R2_PUBLIC_HOSTNAME = "${R2_PUBLIC_HOSTNAME}"
R2_API_TOKEN = "${R2_API_TOKEN}"
R2_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
R2_BUCKET = "${R2_BUCKET}"
CF_WEB_ANALYTICS_TOKEN = "${CF_WEB_ANALYTICS_TOKEN}"
