name: Cloudflare Deploy (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      custom_domain_config:
        required: false
        type: boolean
    secrets:
      CF_ACCOUNT_ID:
        required: true
      CF_ZONE_ID:
        required: true
      R2_API_TOKEN:
        required: true
      R2_ACCESS_KEY_ID:
        required: false
      R2_SECRET_ACCESS_KEY:
        required: false

jobs:
  derive-r2-credentials:
    name: Derive Cloudflare R2 credentials
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      R2_API_TOKEN: ${{ secrets.R2_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID || '' }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps --silent
      - name: Debug environment values
        shell: bash
        env:
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PUBLIC_HOSTNAME: ${{ vars.R2_PUBLIC_HOSTNAME }}
          R2_FORCE_S3: ${{ vars.R2_FORCE_S3 }}
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "R2_BUCKET: $R2_BUCKET"
          echo "R2_PUBLIC_HOSTNAME: $R2_PUBLIC_HOSTNAME"
          echo "R2_FORCE_S3: $R2_FORCE_S3"
          echo "CF_ACCOUNT_ID: $CF_ACCOUNT_ID"
          echo "CF_ZONE_ID: $CF_ZONE_ID"
    
      - name: Derive R2 credentials from Cloudflare API token
        if: ${{ env.R2_ACCESS_KEY_ID == '' || env.R2_SECRET_ACCESS_KEY == '' || env.R2_FORCE_S3 == 'true' }}
        shell: bash
        env:
          R2_API_TOKEN: ${{ secrets.R2_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          R2_FORCE_S3: true
        run: |
          set -euo pipefail
          python <<EOF
          import os
          import requests
  
          api_token = os.environ['R2_API_TOKEN']
          account_id = os.environ['CF_ACCOUNT_ID']
          headers = {
              'Authorization': f'Bearer {api_token}',
              'Content-Type': 'application/json'
          }
          resp = requests.post(
              f'https://api.cloudflare.com/client/v4/accounts/{account_id}/r2/temp-access-credentials',
              headers=headers,
              json={}
          )
          resp.raise_for_status()
          result = resp.json()
          creds = result['result']
          os.makedirs('.r2-credentials', exist_ok=True)
          with open('.r2-credentials/credentials.env', 'w') as f:
              f.write(f'R2_ACCOUNT_ID={account_id}\\n')
              f.write(f'R2_ACCESS_KEY_ID={creds["accessKeyId"]}\\n')
              f.write(f'R2_SECRET_ACCESS_KEY={creds["secretAccessKey"]}\\n')
          EOF
  
      - name: Use provided R2 credentials from secrets
        if: ${{ env.R2_ACCESS_KEY_ID != '' && env.R2_SECRET_ACCESS_KEY != '' }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .r2-credentials
          {
              echo "R2_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}"
              echo "R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}"
              echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}"
          } > .r2-credentials/credentials.env

      - name: Append all environment variables to credentials file
        env:
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PUBLIC_HOSTNAME: ${{ vars.R2_PUBLIC_HOSTNAME }}
          R2_FORCE_S3: ${{ vars.R2_FORCE_S3 }}
          R2_API_TOKEN: ${{ secrets.R2_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }} 
        run: |
          {
            echo "R2_API_TOKEN=$R2_API_TOKEN"
            echo "R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID"
            echo "R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY"
            echo "R2_BUCKET=$R2_BUCKET"
            echo "R2_PUBLIC_HOSTNAME=$R2_PUBLIC_HOSTNAME"
            echo "R2_FORCE_S3=$R2_FORCE_S3"
            echo "CF_ACCOUNT_ID=$CF_ACCOUNT_ID"
            echo "CF_ZONE_ID=$CF_ZONE_ID"
          } >> .r2-credentials/credentials.env
      
      - name: Upload derived R2 credentials artifact
        uses: actions/upload-artifact@v4
        with:
          name: r2-credentials-${{ inputs.environment }}
          path: .r2-credentials
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  build:
    name: Build OpenNext bundle
    runs-on: ubuntu-latest
    needs: derive-r2-credentials
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps --silent
      - name: Download and Install derived credentials
        uses: actions/download-artifact@v4
        with:
          name: r2-credentials-${{ inputs.environment }}
          path: .r2-credentials
      - name: Export credentials to environment
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done < .r2-credentials/credentials.env
      - name: Build with OpenNext
        run: npm run opennext:build
      - name: Ensure all SSR chunks are present in OpenNext bundle
        run: |
          mkdir -p .open-next/server/chunks/ssr
          cp -r .next/server/chunks/ssr/* .open-next/server/chunks/ssr/
          ls -lh .open-next/server/chunks/ssr/
      - name: Upload OpenNext artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-next-bundle
          path: |
            .open-next
            wrangler.toml
          include-hidden-files: true
          if-no-files-found: error

  prepare:
    name: Configure Cloudflare resources
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - name: Install runtime dependencies
        run: npm install --legacy-peer-deps --silent --omit=dev
      - name: Download and Install derived credentials
        uses: actions/download-artifact@v4
        with:
          name: r2-credentials-${{ inputs.environment }}
          path: .r2-credentials
      - name: Export credentials to environment
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done < .r2-credentials/credentials.env
      - name: Debug Cloudflare environment values
        env:
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PUBLIC_HOSTNAME: ${{ vars.R2_PUBLIC_HOSTNAME }}
          R2_FORCE_S3: ${{ vars.R2_FORCE_S3 }}
        run: |
          set -euo pipefail
          for name in CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ZONE_ID R2_BUCKET R2_ACCOUNT_ID R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY; do
            if [ -z "${!name}" ]; then
              echo "::error::${name} is empty at runtime." >&2
              exit 1
            else
              echo "${name} is set"
            fi
          done
      - name: Sync R2 CORS policy
        run: node scripts/configure-r2-cors.js
      - name: Ensure R2 custom domain uses TLS 1.3
        if: ${{ inputs.custom_domain_config }}
        run: node scripts/configure-r2-custom-domain.js

  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - name: Download OpenNext artifact
        uses: actions/download-artifact@v4
        with:
          name: open-next-bundle
          path: .
      - name: Download and Install derived credentials
        uses: actions/download-artifact@v4
        with:
          name: r2-credentials-${{ inputs.environment }}
          path: .r2-credentials
      - name: Export credentials to environment
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done < .r2-credentials/credentials.env
      - name: Render Wrangler config with environment secrets
        run: |
          set -euo pipefail
          envsubst '${CLOUDFLARE_ACCOUNT_ID} ${CLOUDFLARE_ZONE_ID} ${R2_PUBLIC_HOSTNAME} ${R2_BUCKET} ${CF_WEB_ANALYTICS_TOKEN}' < wrangler.toml > wrangler.resolved.toml
      - name: Deploy to environment
        run: |
          set -euo pipefail
          CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
          CLOUDFLARE_ZONE_ID="$CLOUDFLARE_ZONE_ID" \
          npx --yes wrangler@4 deploy --config wrangler.resolved.toml --env ${{ inputs.environment }}
      - name: Confirm latest deployment
        run: |
          set -euo pipefail
          CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
          npx --yes wrangler@4 deployments status --config wrangler.resolved.toml --env ${{ inputs.environment }}
