name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        # Use a tolerant install so CI doesn't fail on dev-only peerDependency conflicts
        run: npm install --legacy-peer-deps --silent

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build with OpenNext
        run: npm run opennext:build

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verify Cloudflare secrets
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
        run: |
          set -euo pipefail

          for name in CF_API_TOKEN CF_ACCOUNT_ID CF_PROJECT_NAME; do
            if [ -z "${!name}" ]; then
              echo "::error::Missing GitHub secret ${name}. Please create it in Settings > Secrets and variables > Actions." >&2
              exit 1
            fi
          done

      - name: Validate Cloudflare account access
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          set -euo pipefail

          npx --yes wrangler@4 whoami --config wrangler.toml --account "$CLOUDFLARE_ACCOUNT_ID"

      - name: Verify Cloudflare Pages project exists
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
        run: |
          set -euo pipefail

          api_url="https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PROJECT_NAME"
          tmp_body=$(mktemp)
          trap 'rm -f "$tmp_body"' EXIT

          if ! command -v jq >/dev/null 2>&1; then
            echo "::error::jq is required to validate the Cloudflare Pages project response."
            exit 1
          fi

          if ! curl --silent --show-error --fail-with-body \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$api_url" \
            -o "$tmp_body"; then
            echo "::group::Cloudflare API response"
            cat "$tmp_body" || true
            echo "::endgroup::"
            echo "::error::Cloudflare Pages project \"$CLOUDFLARE_PROJECT_NAME\" was not found or is inaccessible under account $CLOUDFLARE_ACCOUNT_ID."
            exit 1
          fi

          if ! jq -e '.success == true' "$tmp_body" >/dev/null; then
            echo "::group::Cloudflare API response"
            jq '.' "$tmp_body" || cat "$tmp_body"
            echo "::endgroup::"
            echo "::error::Unexpected response when verifying Cloudflare Pages project \"$CLOUDFLARE_PROJECT_NAME\"."
            exit 1
          fi

          if ! jq -e --arg name "$CLOUDFLARE_PROJECT_NAME" '.result.name == $name' "$tmp_body" >/dev/null; then
            echo "::group::Cloudflare API response"
            jq '.' "$tmp_body" || cat "$tmp_body"
            echo "::endgroup::"
            echo "::error::Cloudflare API returned a different project than expected."
            exit 1
          fi

      - name: Deploy with OpenNext
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
        run: |
          npm run opennext:deploy

