name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:



jobs:
  validate:
    name: Lint & unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps --silent
      - name: Lint
        run: npm run lint
        working-directory: ./
      - name: Test with coverage thresholds
        env:
          CI: true
        run: npm test

  deploy:
    name: Deploy to Cloudflare Workers
    needs: validate
    uses: ./.github/workflows/cloudflare-reusable.yml
    with:
      environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'dev' }}
      branch: ${{ github.ref_name }}
      custom_domain_config: ${{ github.ref == 'refs/heads/master' }}
    secrets:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
