name: Deprecated - use Deploy to Cloudflare Workers

on:
  workflow_dispatch:

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::This workflow has been replaced by .github/workflows/deploy-cloudflare-workers.yml."
          exit 1

