
name: Unit tests

on:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        # package-lock.json is tracked; use npm ci for clean, reproducible installs
        run: npm ci

      - name: Run Jest unit tests (coverage disabled for speed)
        # Following GitHub's Node.js CI guidance, run npm test (Jest) without coverage enforcement to keep CI fast.
        run: npm test -- --ci --reporters=default --coverage=false

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
